### ISSUE TITLE
pypi version incompatible with new numpy

### ISSUE THREAD

**Issue by RadostW** [FCS-analysis/PyCorrFit#210]
Problem:

Loading `.fcs` files gives the following error:

```
  File "./venv/lib/python3.10/site-packages/pycorrfit/readfiles/read_FCS_Confocor3.py", line 147, in openFCS_Multiple
    trace.append((np.float(row[3])*1000,
  File "./venv/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(__former_attrs__[attr], name=None)
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

---

Source of the problem:

Current installation via pip pulls the following packages:

```
asteval==1.0.6
dill==0.4.0
lmfit==1.3.3
numpy==2.2.6
pycorrfit==1.1.7
PyYAML==6.0.2
scipy==1.15.3
uncertainties==3.2.3
```

This numpy is too new for 1.1.7 release code because of `numpy.float` removal (this is now `numpy.float64`). 

---

Solution:

Code on github is good so just pushing a new release should fix the issue.

**Comment by paulmueller** [comment]
@RadostW Thanks for the issue. Looks like the solution would be to pin numpy to `numpy<2` in `setup.py`. I would be happy to merge a PR for this 👍

**Comment by RadostW** [comment]
pip installed code directly from github works fine with `numpy==2.2.6`
(installed like this `python3 -m pip install git+https://github.com/FCS-analysis/PyCorrFit.git`)

Source hosted on pypi is much older (installed like this `python3 -m pip install pycorrfit`), Looking at `https://pypi.org/project/pycorrfit/`it seems it's just out of sync by a few years.

**Comment by RadostW** [comment]
Is there a chance for the current github state to become "1.1.8 release" and to be pushed to pypi?

**Comment by RadostW** [comment]
`numpy 2.0` incompatibility is fixed now, thank you!

There is now only a *tiny* incompatibility with new versions of `scipy`. I have prepared a patch #211 which addresses the issue.
